# Generated by Django 6.0.4 on 2026-05-02 00:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_role_roleassignment_alter_employeeprofile_options_and_more'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('code', models.SlugField(help_text='Для внутренних операций', unique=True, verbose_name='Код')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='Иконка (emoji/css)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('requires_contract', models.BooleanField(default=False, verbose_name='Требуется договор')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Комиссия платежной системы в процентах', max_digits=5, verbose_name='Комиссия (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер договора')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('SUSPENDED', 'Приостановлен'), ('COMPLETED', 'Завершен'), ('TERMINATED', 'Расторгнут')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Для рассрочки или абонемента', max_digits=10, null=True, verbose_name='Ежемесячная плата (руб)')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Файл договора')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('PACKAGE', 'Пакет уроков'), ('SINGLE', 'Разовое занятие'), ('MONTHLY', 'Ежемесячная оплата'), ('EVENT', 'Мероприятие'), ('OTHER', 'Другое')], default='PACKAGE', max_length=20, verbose_name='Тип оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Уже оплачено (руб)')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена'), ('REFUNDED', 'Возвращена')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Номер счета')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Время оплаты')),
                ('refund_reason', models.TextField(blank=True, verbose_name='Причина возврата')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Время возврата')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренние примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.client', verbose_name='Клиент')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.contract', verbose_name='Договор')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentmethod', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер счета')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб)')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='Дата выставления')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлен'), ('PAID', 'Оплачен'), ('CANCELLED', 'Отменен')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('items', models.JSONField(blank=True, default=list, help_text='[{"name": "Пакет 8 занятий", "quantity": 1, "price": 5000}]', verbose_name='Позиции')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('sent_to_email', models.EmailField(blank=True, max_length=254, verbose_name='Отправлено на email')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='PDF файл')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='payments.payment', verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('lesson_count', models.PositiveIntegerField(verbose_name='Количество занятий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Скидка при покупке пакета', max_digits=5, verbose_name='Скидка (%)')),
                ('validity_days', models.PositiveIntegerField(default=90, help_text='Срок действия пакета с момента покупки', verbose_name='Действителен (дней)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, help_text='Для выделения в прайсе', verbose_name='Популярный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='lessons.lessontype', verbose_name='Тип занятий')),
            ],
            options={
                'verbose_name': 'Пакет уроков',
                'verbose_name_plural': 'Пакеты уроков',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='lesson_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='payments.paymentpackage', verbose_name='Пакет уроков'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', '-created_at'], name='payments_pa_client__ef8bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'due_date'], name='payments_pa_status_0d3455_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'client'], name='payments_co_status_4f7ff7_idx'),
        ),
    ]
