# Generated by Django 6.0.4 on 2026-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20260502_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая сумма комиссии', max_digits=10, null=True, verbose_name='Сумма комиссии (руб)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Комиссия платежной системы в процентах', max_digits=5, null=True, verbose_name='Комиссия банка (%)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, help_text='Для рассрочки: 1/2, 2/2 и т.д.', null=True, verbose_name='№ платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_installments',
            field=models.PositiveIntegerField(blank=True, help_text='Общее количество платежей в рассрочке', null=True, verbose_name='Всего платежей'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ONCE', 'Разовый платёж'), ('BANK_2', 'Банковская рассрочка 2 платежа'), ('BANK_3', 'Банковская рассрочка 3 платежа'), ('BANK_6', 'Банковская рассрочка 6 платежей'), ('SCHOOL_2', 'Рассрочка школы 2 платежа'), ('SCHOOL_3', 'Рассрочка школы 3 платежа'), ('SCHOOL_6', 'Рассрочка школы 6 платежей')], default='ONCE', max_length=20, verbose_name='Тип оплаты'),
        ),
    ]
