# Generated by Django 6.0.4 on 2026-05-01 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('OWNER', 'Владелец'), ('ADMIN', 'Администратор'), ('MANAGER', 'Менеджер'), ('TEACHER', 'Преподаватель'), ('STUDENT', 'Ученик')], max_length=20, unique=True, verbose_name='Код роли')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('can_view_clients', models.BooleanField(default=False, verbose_name='Просмотр клиентов')),
                ('can_edit_clients', models.BooleanField(default=False, verbose_name='Редактирование клиентов')),
                ('can_view_finance', models.BooleanField(default=False, verbose_name='Просмотр финансов')),
                ('can_edit_finance', models.BooleanField(default=False, verbose_name='Редактирование финансов')),
                ('can_view_schedule', models.BooleanField(default=False, verbose_name='Просмотр расписания')),
                ('can_edit_schedule', models.BooleanField(default=False, verbose_name='Редактирование расписания')),
                ('can_view_tasks', models.BooleanField(default=False, verbose_name='Просмотр задач')),
                ('can_create_tasks', models.BooleanField(default=False, verbose_name='Создание задач')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Управление пользователями')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Просмотр отчетов')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Настройки системы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная роль')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Профиль сотрудника', 'verbose_name_plural': 'Профили сотрудников'},
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_interaction_date',
            field=models.DateField(blank=True, editable=False, help_text='Автообновляется при создании взаимодействия', null=True, verbose_name='Дата последнего взаимодействия'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки о клиенте'),
        ),
        migrations.AddField(
            model_name='client',
            name='silent_days',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Сколько дней прошло с последнего взаимодействия', verbose_name='Дней без активности'),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, help_text='Откуда пришел: рекомендация, реклама, сайт и т.д.', max_length=50, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('SILENT', 'Молчун (>14 дней)'), ('LOST', 'Потеряшка (>30 дней)'), ('CANCELLED', 'Расторгнул'), ('POTENTIAL', 'Потенциальный')], default='POTENTIAL', help_text='Автообновляется на основе взаимодействий', max_length=20, verbose_name='Статус клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую: фортепиано, вечерние, скидка', max_length=200, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_manage_resources',
            field=models.BooleanField(default=False, verbose_name='Управление оборудованием'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_manage_rooms',
            field=models.BooleanField(default=False, verbose_name='Управление аудиториями'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_on_leave',
            field=models.BooleanField(default=False, verbose_name='В отпуске/на больничном'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец отпуска/больничного'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', '-last_interaction_date'], name='core_client_status_6144ac_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active', 'status'], name='core_client_is_acti_8d7290_idx'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='primary_role',
            field=models.ForeignKey(blank=True, help_text='Текущая рабочая роль', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profiles', to='core.role', verbose_name='Основная роль'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='assigned_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.role'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('user', 'role')},
        ),
    ]
