# Generated by Django 6.0.4 on 2026-05-02 00:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_roleassignment_alter_employeeprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.coursecategory')),
            ],
            options={
                'verbose_name': 'Категория курса',
                'verbose_name_plural': 'Категории курсов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('full_description', models.TextField(blank=True, help_text='Подробное описание для прайса', verbose_name='Полное описание')),
                ('level', models.CharField(choices=[('BEGINNER', 'Начинающий'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый'), ('PROFESSIONAL', 'Профессиональный')], default='BEGINNER', max_length=20, verbose_name='Уровень')),
                ('duration', models.CharField(choices=[('1_month', '1 месяц'), ('3_months', '3 месяца'), ('6_months', '6 месяцев'), ('9_months', '9 месяцев'), ('1_year', '1 год'), ('open', 'Открытая длительность')], default='3_months', max_length=20, verbose_name='Длительность')),
                ('curriculum', models.TextField(blank=True, help_text='Перечень тем/модулей через запятую или список', verbose_name='Программа курса')),
                ('lessons_per_week', models.PositiveIntegerField(default=1, verbose_name='Уроков в неделю')),
                ('lesson_duration', models.PositiveIntegerField(default=60, verbose_name='Длительность урока (мин)')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Цена за полный курс или за месяц', max_digits=10, verbose_name='Базовая цена (руб)')),
                ('price_per_lesson', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за одно занятие (руб)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('max_students', models.PositiveIntegerField(default=10, help_text='Максимальное количество студентов на курсе', verbose_name='Максимум студентов')),
                ('materials_url', models.URLField(blank=True, verbose_name='Ссылка на материалы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('instructors', models.ManyToManyField(blank=True, related_name='courses_taught', to='core.employeeprofile', verbose_name='Преподаватели')),
                ('prerequisite_courses', models.ManyToManyField(blank=True, related_name='followup_courses', to='core.course', verbose_name='Необходимые предыдущие курсы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.coursecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('ACTIVE', 'Активен'), ('COMPLETED', 'Завершен'), ('DROPPED', 'Брошен'), ('PAUSED', 'Приостановлен')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('NOT_PAID', 'Не оплачено'), ('PARTIAL', 'Частично оплачено'), ('PAID', 'Оплачено')], default='NOT_PAID', max_length=20, verbose_name='Статус оплаты')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата окончания')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('completed_lessons', models.PositiveIntegerField(default=0, verbose_name='Проведено уроков')),
                ('total_lessons', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего уроков')),
                ('enrolled_price', models.DecimalField(decimal_places=2, help_text='Цена, по которой записался студент (может отличаться от базовой)', max_digits=10, verbose_name='Цена при записи (руб)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Оплачено (руб)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('source', models.CharField(blank=True, help_text='Откуда записался: сайт, телефон, рекомендация', max_length=100, verbose_name='Источник записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.employeeprofile', verbose_name='Назначенный преподаватель')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.client', verbose_name='Студент')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course', verbose_name='Курс')),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Записал')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'level'], name='core_course_is_acti_7d830e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['client', '-created_at'], name='core_enroll_client__9fecab_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='core_enroll_course__00616f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'client', 'start_date')},
        ),
    ]
