# Generated by Django 6.0.4 on 2026-05-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursecategory_course_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_is_acti_7d830e_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая цена к оплате (со скидкой). Если не указано, используется базовая цена', max_digits=10, null=True, verbose_name='Акционная цена (руб)'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.PositiveIntegerField(default=12, help_text='Общее количество занятий (включая самостоятельную практику). Например: 8 занятий с преподом + 4 самостоятельных = 12', verbose_name='Всего занятий в курсе'),
        ),
        migrations.AlterField(
            model_name='course',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Полная стоимость курса для договора и прайс-листа (без скидок)', max_digits=10, verbose_name='Базовая цена курса (руб)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Раздел, к которому относится курс (например: DJ-инг, Звукозапись, Мастер-классы)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.coursecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='curriculum',
            field=models.TextField(blank=True, help_text='Перечень тем/модулей через запятую или список. Что будет изучать студент', verbose_name='Программа курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание курса для списка (1-2 предложения)', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('1_month', '1 месяц'), ('3_months', '3 месяца'), ('6_months', '6 месяцев'), ('9_months', '9 месяцев'), ('1_year', '1 год'), ('open', 'Открытая длительность (по желанию)')], default='3_months', help_text='Рекомендуемая длительность прохождения курса', max_length=20, verbose_name='Длительность курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, help_text='Подробное описание для договора и прайс-листа', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Курс доступен для записи', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Показывать в разделе популярных курсов', verbose_name='Популярный'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_duration',
            field=models.PositiveIntegerField(default=60, help_text='Стандартная длительность одного занятия в минутах (45, 60, 90)', verbose_name='Длительность занятия (минут)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_url',
            field=models.URLField(blank=True, help_text='Google Drive, Dropbox или другая ссылка на учебные материалы', verbose_name='Ссылка на материалы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=10, help_text='Максимальное количество студентов, которые могут быть записаны на курс одновременно', verbose_name='Максимум студентов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Краткое название курса, например: DJ Basics, Продвинутый миксинг', max_length=200, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, help_text='Если есть, укажите курсы, которые нужно пройти перед этим', related_name='followup_courses', to='core.course', verbose_name='Необходимые предыдущие курсы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='URL-адрес курса на латинице, например: dj-basics', unique=True, verbose_name='Слаг'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'name'], name='core_course_is_acti_df0538_idx'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons_per_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_per_lesson',
        ),
    ]
