# Generated by Django 6.0.4 on 2026-05-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_course_core_course_is_acti_7d830e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisite_courses',
        ),
    ]
