# Generated by Django 6.0.4 on 2026-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_prerequisite_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_practice_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Отработано практики (минуты)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='installment_bank_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Комиссия банка (%)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='installment_type',
            field=models.CharField(choices=[('NONE', 'Разовый платёж'), ('BANK_2', 'Банковская рассрочка 2 платежа'), ('BANK_3', 'Банковская рассрочка 3 платежа'), ('BANK_6', 'Банковская рассрочка 6 платежей'), ('SCHOOL_2', 'Рассрочка школы 2 платежа'), ('SCHOOL_3', 'Рассрочка школы 3 платежа'), ('SCHOOL_6', 'Рассрочка школы 6 платежей')], default='NONE', max_length=20, verbose_name='Тип рассрочки'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_unlimited_practice',
            field=models.BooleanField(default=False, verbose_name='Безлимитная практика'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_practice_hours',
            field=models.PositiveIntegerField(default=30, help_text='0 для безлимита', verbose_name='Часов практики'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Отработано с преподавателем'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='total_lessons',
            field=models.PositiveIntegerField(default=10, verbose_name='Всего занятий в курсе'),
        ),
    ]
