# Generated by Django 6.0.4 on 2026-05-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_enrollment_actual_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Микшерный пульт Mackie, Пианино Yamaha', max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('EQUIPMENT', 'Оборудование'), ('INSTRUMENT', 'Музыкальный инструмент'), ('SOFTWARE', 'Программное обеспечение'), ('MATERIAL', 'Расходные материалы'), ('OTHER', 'Другое')], default='EQUIPMENT', max_length=20, verbose_name='Тип')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Сколько единиц доступно', verbose_name='Количество')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('condition', models.CharField(choices=[('GOOD', 'Хорошее'), ('FAIR', 'Удовлетворительное'), ('BAD', 'Требует ремонта'), ('MAINTENANCE', 'В ремонте')], default='GOOD', max_length=20, verbose_name='Состояние')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена аренды/час (руб)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Студия 1, Класс А-101', max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('STUDIO', 'Студия'), ('CLASSROOM', 'Учебный класс'), ('PRACTICE', 'Кабинет практики'), ('MEETING', 'Зал для совещаний'), ('OTHER', 'Другое')], default='CLASSROOM', max_length=20, verbose_name='Тип')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Максимум человек одновременно', verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, help_text='Особенности помещения', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.CreateModel(
            name='RoomResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_room', models.PositiveIntegerField(default=1, verbose_name='Количество в этой аудитории')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resources', to='core.resource')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_resources', to='core.room')),
            ],
            options={
                'verbose_name': 'Ресурс в аудитории',
                'verbose_name_plural': 'Ресурсы в аудиториях',
                'unique_together': {('room', 'resource')},
            },
        ),
    ]
