# Generated by Django 6.0.5 on 2026-05-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resource_room_remove_course_max_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('GENERAL', 'Общий'), ('IMPORTANT', 'Важное'), ('REMINDER', 'Напоминание'), ('NOTE', 'Заметка')], default='GENERAL', max_length=20, verbose_name='Тип комментария')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_internal', models.BooleanField(default=True, help_text='Если отмечено, комментарий виден только сотрудникам', verbose_name='Только для сотрудников')),
                ('is_pinned', models.BooleanField(default=False, help_text='Закрепить комментарий вверху списка', verbose_name='Закреплён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reminder_date', models.DateTimeField(blank=True, help_text='Дата напоминания (если тип = Reminder)', null=True, verbose_name='Напомнить до')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.client', verbose_name='Клиент')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий к клиенту',
                'verbose_name_plural': 'Комментарии к клиентам',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='core_client_client__b5f82d_idx'), models.Index(fields=['is_internal', 'is_pinned'], name='core_client_is_inte_7ca1f5_idx')],
            },
        ),
    ]
