# Generated by Django 6.0.5 on 2026-05-09 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clientcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='client',
            name='balance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Бонусные баллы клиента', max_digits=10, verbose_name='Баланс бонусов'),
        ),
        migrations.AddField(
            model_name='client',
            name='balance_contract',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Остаток средств по договору', max_digits=10, verbose_name='Баланс договора'),
        ),
        migrations.AddField(
            model_name='client',
            name='color',
            field=models.PositiveIntegerField(default=1, help_text='ID цвета для визуализации в списках', verbose_name='Цвет клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_payment_date',
            field=models.DateField(blank=True, help_text='Дата первого платежа', null=True, verbose_name='Дата первой оплаты'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_attend_date',
            field=models.DateField(blank=True, help_text='Дата последнего посещения занятия', null=True, verbose_name='Посл. посещение'),
        ),
        migrations.AddField(
            model_name='client',
            name='lesson_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество оставшихся уроков', verbose_name='Остаток уроков'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_lesson_date',
            field=models.DateField(blank=True, help_text='Дата следующего запланированного занятия', null=True, verbose_name='След. занятие'),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, choices=[('SOCIAL_MEDIA', 'Соцсети'), ('FRIENDS', 'От друзей'), ('GOOGLE', 'Google/Yandex'), ('ADVERTISING', 'Реклама'), ('OTHER', 'Другое')], help_text='Откуда пришел: рекомендация, реклама, сайт и т.д.', max_length=50, verbose_name='Источник'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_manager'], name='core_client_assigne_15c534_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_attend_date'], name='core_client_last_at_e60284_idx'),
        ),
    ]
