# Generated by Django 6.0.5 on 2026-05-09 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client_assigned_manager_client_balance_bonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesson_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('category', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('unlimited', 'Unlimited')], default='individual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientcomment',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Client Comment', 'verbose_name_plural': 'Client Comments'},
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_assigne_15c534_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_last_at_e60284_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientcomment',
            name='core_client_client__b5f82d_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientcomment',
            name='core_client_is_inte_7ca1f5_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, help_text='Откуда пришел: рекомендация, реклама, сайт и т.д.', max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.client'),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='comment_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('IMPORTANT', 'Important'), ('REMINDER', 'Reminder'), ('NOTE', 'Note')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='is_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='client',
            name='assigned_manager',
        ),
        migrations.RemoveField(
            model_name='client',
            name='balance_bonus',
        ),
        migrations.RemoveField(
            model_name='client',
            name='balance_contract',
        ),
        migrations.RemoveField(
            model_name='client',
            name='color',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_payment_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_attend_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lesson_count',
        ),
        migrations.RemoveField(
            model_name='client',
            name='next_lesson_date',
        ),
    ]
