# Generated by Django 6.0.4 on 2026-05-01 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, help_text='Например: 📞, ✉️', max_length=20, verbose_name='Иконка (emoji/css)')),
                ('color', models.CharField(default='#6c757d', help_text='Hex цвет для визуализации', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тип взаимодействия',
                'verbose_name_plural': 'Типы взаимодействий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('note', models.TextField(blank=True, verbose_name='Заметки')),
                ('date_time', models.DateTimeField(blank=True, help_text='Если не указано, считается событием без точного времени', null=True, verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('COMPLETED', 'Выполнено'), ('CANCELLED', 'Отменено')], default='PLANNED', max_length=20, verbose_name='Статус')),
                ('is_reminder', models.BooleanField(default=False, verbose_name='Напоминание')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата напоминания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('interaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='interactions.interactiontype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'ordering': ['-date_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactions.interaction', verbose_name='Взаимодействие')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['client', '-date_time'], name='interaction_client__a4d0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['status', 'is_reminder'], name='interaction_status_6767b5_idx'),
        ),
    ]
