# Generated by Django 6.0.4 on 2026-05-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_enrollment_actual_end_date_and_more'),
        ('interactions', '0001_initial'),
        ('lessons', '0003_lesson_cancellation_reason_lesson_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LESSON_REMINDER_24H', 'Напоминание о занятии за 24 часа'), ('LESSON_REMINDER_3H', 'Напоминание о занятии за 3 часа'), ('PAYMENT_REMINDER', 'Напоминание об оплате'), ('COURSE_COMPLETED', 'Курс завершён'), ('CUSTOM', 'Произвольное уведомление')], max_length=50)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('send_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push-уведомление'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20, verbose_name='Способ')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает отправки'), ('SENT', 'Отправлено'), ('FAILED', 'Ошибка отправки')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Планируемая отправка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.client', verbose_name='Клиент')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.enrollment', verbose_name='Запись на курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='lessons.lesson', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='interaction_status_84f569_idx')],
            },
        ),
    ]
