# Generated by Django 6.0.1 on 2026-03-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcabinetprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
    ]
