# Generated by Django 6.0.1 on 2026-03-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cabinet', '0002_clientcabinetprofile_phone'),
        ('clients', '0006_interaction_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcabinetprofile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент CRM'),
        ),
    ]
