# Generated by Django 6.0.1 on 2026-02-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_interaction'),
        ('products', '0006_alter_payment_due_date_alter_payment_paid_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='manager',
        ),
        migrations.AddField(
            model_name='interaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Назначена'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='call_initiated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала звонка'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='call_logged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время фиксации результата'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Можно редактировать'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.enrollment', verbose_name='Запись на продукт'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактирован'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_reminder',
            field=models.BooleanField(default=False, verbose_name='Напоминание'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='original_content',
            field=models.TextField(blank=True, verbose_name='Исходный текст'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('note', 'Комментарий'), ('task', 'Задача'), ('call', 'Звонок'), ('enrollment', 'Запись на занятие')], max_length=20, verbose_name='Тип'),
        ),
    ]
