# Generated by Django 6.0.1 on 2026-02-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_manager_interaction_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField(verbose_name='Старый текст')),
                ('new_content', models.TextField(verbose_name='Новый текст')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='clients.interaction', verbose_name='Взаимодействие')),
            ],
            options={
                'verbose_name': 'Правка взаимодействия',
                'verbose_name_plural': 'Правки взаимодействий',
                'ordering': ['-edited_at'],
            },
        ),
    ]
