# Generated by Django 6.0.1 on 2026-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_interactionedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
