# Generated by Django 6.0.1 on 2026-03-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_interaction_is_completed'),
        ('lessons', '0008_alter_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Занятие'),
        ),
    ]
