# Generated by Django 6.0.4 on 2026-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_interaction_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('active', 'Активный'), ('inactive', 'Неактивный')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('note', 'Комментарий'), ('task', 'Задача'), ('call', 'Звонок'), ('enrollment', 'Запись на занятие')], db_index=True, max_length=20, verbose_name='Тип'),
        ),
    ]
