# Generated by Django 6.0.4 on 2026-05-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('color', models.CharField(default='#3788d8', help_text='HEX код цвета', max_length=7, verbose_name='Цвет в календаре')),
                ('duration_default', models.PositiveIntegerField(default=60, verbose_name='Длительность по умолчанию (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('rescheduled', 'Перенесено')], default='planned', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.client', verbose_name='Клиент')),
                ('parent_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='lessons.lesson', verbose_name='Исходное занятие')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.employeeprofile', verbose_name='Преподаватель')),
                ('lesson_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lessons.lessontype', verbose_name='Тип занятия')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки о занятии')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='lessons.lesson', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time'], name='lessons_les_start_t_1fb529_idx'),
        ),
    ]
