# Generated by Django 6.0.4 on 2026-05-02 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_course_core_course_is_acti_7d830e_idx_and_more'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type_detail',
            field=models.CharField(choices=[('STANDARD', 'Занятие с преподавателем'), ('PRACTICE', 'Самостоятельная практика')], default='STANDARD', help_text='Занятие с преподавателем или самостоятельная практика', max_length=20, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Опционально: не заполняется для самостоятельной практики', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.employeeprofile', verbose_name='Преподаватель'),
        ),
    ]
