# Generated by Django 6.0.4 on 2026-05-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_enrollment_actual_end_date_and_more'),
        ('lessons', '0002_lesson_lesson_type_detail_alter_lesson_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность (минут)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.enrollment', verbose_name='Запись на курс'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Студент не пришёл')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'start_time'], name='lessons_les_teacher_71a5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['client', 'start_time'], name='lessons_les_client__7b570d_idx'),
        ),
    ]
