# Generated by Django 6.0.1 on 2026-01-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lessons.room', verbose_name='Кабинет'),
            preserve_default=False,
        ),
    ]
