# Generated by Django 6.0.4 on 2026-05-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resource_room_remove_course_max_students_and_more'),
        ('lessons', '0003_lesson_cancellation_reason_lesson_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='core.resource', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.room', verbose_name='Аудитория'),
        ),
    ]
