# Generated by Django 6.0.1 on 2026-03-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lesson', 'Занятие с преподавателем'), ('practice', 'Самостоятельная практика')], default='lesson', max_length=20, verbose_name='Тип'),
        ),
    ]
