# Generated by Django 6.0.1 on 2026-03-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('lessons', '0006_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='balance_charged',
            field=models.BooleanField(default=False, help_text='True если занятие уже списало баланс клиента', verbose_name='Баланс списан'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения статуса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_status_changed', to='core.userprofile', verbose_name='Изменил статус'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', '📅 Запланировано'), ('confirmed', '✅ Подтверждено'), ('in_progress', '🔄 В процессе'), ('completed', '✔️ Проведено'), ('cancelled_with_charge', '❌ Отменено со списанием'), ('cancelled_without_charge', '⚠️ Отменено без списания')], default='scheduled', max_length=30, verbose_name='Статус'),
        ),
    ]
