# Generated by Django 6.0.1 on 2026-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_balance_charged_lesson_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', '📅 Запланировано'), ('confirmed', '✅ Подтверждено'), ('in_progress', '🔄 В процессе'), ('completed', '✔️ Проведено'), ('no_show', '❌ Не явился'), ('cancelled_early', '⚠️ Отменено заранее')], default='scheduled', max_length=30, verbose_name='Статус'),
        ),
    ]
