# Generated by Django 6.0.4 on 2026-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lesson', 'Занятие с преподавателем'), ('practice', 'Самостоятельная практика')], db_index=True, default='lesson', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', '📅 Запланировано'), ('confirmed', '✅ Подтверждено'), ('in_progress', '🔄 В процессе'), ('completed', '✔️ Проведено'), ('no_show', '❌ Не явился'), ('cancelled_early', '⚠️ Отменено заранее')], db_index=True, default='scheduled', max_length=30, verbose_name='Статус'),
        ),
    ]
