# Generated by Django 6.0.1 on 2026-01-30 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('product_type', models.CharField(choices=[('lesson', 'Индивидуальное занятие'), ('course', 'Курс'), ('certificate', 'Подарочный сертификат'), ('studio_rental', 'Аренда студии'), ('trial', 'Пробное занятие')], max_length=20, verbose_name='Тип')),
                ('base_lessons', models.PositiveIntegerField(default=0, verbose_name='Базовое количество занятий')),
                ('base_practices', models.PositiveIntegerField(default=0, verbose_name='Базовое количество практик')),
                ('unlimited_practice', models.BooleanField(default=False, verbose_name='Безлимитная практика')),
                ('unlimited_duration_months', models.PositiveIntegerField(default=0, help_text='Если безлимит включён, указывается срок в месяцах', verbose_name='Срок безлимита (мес)')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена по умолчанию')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
