# Generated by Django 6.0.1 on 2026-01-30 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_total', models.PositiveIntegerField(default=0, verbose_name='Всего занятий')),
                ('lessons_used', models.PositiveIntegerField(default=0, verbose_name='Использовано занятий')),
                ('practices_total', models.PositiveIntegerField(default=0, verbose_name='Всего практик')),
                ('practices_used', models.PositiveIntegerField(default=0, verbose_name='Использовано практик')),
                ('unlimited_practice', models.BooleanField(default=False, verbose_name='Безлимитная практика')),
                ('unlimited_end_date', models.DateField(blank=True, help_text='Если безлимит включён, указывается дата окончания', null=True, verbose_name='Окончание безлимита')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фактическая цена')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен полностью')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('archived', 'Архив')], default='active', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Продукт (шаблон)')),
            ],
            options={
                'verbose_name': 'Запись на продукт',
                'verbose_name_plural': 'Записи на продукты',
                'ordering': ['-created_at'],
            },
        ),
    ]
