# Generated by Django 6.0.1 on 2026-01-30 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название способа оплаты')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card_transfer', 'Перевод на карту'), ('bank_account', 'Расчётный счёт')], max_length=20, verbose_name='Тип оплаты')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Например: 1.5 для 1.5%', max_digits=5, verbose_name='Комиссия (%)')),
                ('commission_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Например: 30 для 30 ₽', max_digits=10, verbose_name='Фиксированная комиссия (₽)')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_by_client', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма от клиента')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма получена школой')),
                ('payment_method_name', models.CharField(max_length=100, verbose_name='Способ оплаты (на момент оплаты)')),
                ('payment_type', models.CharField(max_length=20, verbose_name='Тип оплаты (на момент оплаты)')),
                ('commission_percent_used', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Использованная комиссия (%)')),
                ('commission_fixed_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Использованная фикс. комиссия (₽)')),
                ('is_installment', models.BooleanField(default=False, verbose_name='Рассрочка')),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер платежа')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.enrollment', verbose_name='Запись на продукт')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
