# Generated by Django 6.0.1 on 2026-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='installment_parts',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оставьте пустым для единовременной оплаты. Максимум — 12.', null=True, verbose_name='Количество платежей при рассрочке'),
        ),
    ]
