# Generated by Django 6.0.1 on 2026-02-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_payment_due_date_alter_payment_paid_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
